DATALOADER:
  TRAIN_X:
    BATCH_SIZE: 1536
    SAMPLER: "RandomClassSampler"
    N_INS: 8
  TEST:
    BATCH_SIZE: 512
    N_INS: 16
  NUM_WORKERS: 16
  K_TRANSFORMS: 1

INPUT:
  SIZE: (224, 224)
  INTERPOLATION: "bicubic"
  PIXEL_MEAN: [0.48145466, 0.4578275, 0.40821073]
  PIXEL_STD: [0.26862954, 0.26130258, 0.27577711]
  RRCROP_SCALE: (0.25, 1.0)
  TRANSFORMS: ["random_resized_crop", "random_flip", 'colorjitter', 'gaussian_noise', "normalize"]
OPTIM:
  NAME: "adam"
  LR: 0.0002
  MAX_EPOCH: 30
  LR_SCHEDULER: "cosine"
  WARMUP_EPOCH: 1
  WARMUP_TYPE: "constant"
  WARMUP_CONS_LR: 1e-5

TRAIN:
  PRINT_FREQ: 10
  CHECKPOINT_FREQ: 10
TEST:
  NO_TEST: True
MODEL:
  BACKBONE:
    NAME: "ViT-B/32"

TRAINER:
  COCOOP:
    N_CTX: 2
    CTX_INIT: " ?"
    PREC: "fp16"