_BASE_: "base_r50_4x_clip.yaml"
MODEL:
  META_ARCHITECTURE: "CustomRCNNINS"
  ROI_BOX_HEAD:
    USE_ZEROSHOT_CLS: True
    ZEROSHOT_WEIGHT_DIM: 512
    ZEROSHOT_WEIGHT_PATH: 'checkpoints/visual_prompt_model.pt'
    USE_BIAS: -2.0
  ROI_HEADS:
    NAME: InsDeticCascadeROIHeads
SOLVER:
  LR_SCHEDULER_NAME: "WarmupCosineLR"
  CHECKPOINT_PERIOD: 30000
  WARMUP_ITERS: 10000
  WARMUP_FACTOR: 0.0001
  USE_CUSTOM_SOLVER: True
  OPTIMIZER: "ADAMW"
  MAX_ITER: 90000
  IMS_PER_BATCH: 64
  BASE_LR: 0.0002
  CLIP_GRADIENTS:
    ENABLED: True
TEST:
  EVAL_PERIOD: 45000
DATASETS:
  TRAIN: ("lvis_v1_train_norare",)
MAX_NUM_BOX:
  5