_BASE_: "base_r50_4x_clip.yaml"
MODEL:
  ROI_BOX_HEAD:
    USE_ZEROSHOT_CLS: True
    ZEROSHOT_WEIGHT_DIM: 512
    ZEROSHOT_WEIGHT_PATH: 'datasets/metadata/lvis_gpt3_text-davinci-002_features_author.npy'
    USE_BIAS: -2.0
SOLVER:
  AMP:
    ENABLED: True
  LR_SCHEDULER_NAME: "WarmupCosineLR"
  CHECKPOINT_PERIOD: 120000
  WARMUP_ITERS: 24000
  WARMUP_FACTOR: 0.0001
  USE_CUSTOM_SOLVER: True
  OPTIMIZER: "ADAMW"
  STEPS: (80000,)
  MAX_ITER: 240000
  IMS_PER_BATCH: 24
  BASE_LR: 0.0002
  CLIP_GRADIENTS:
    ENABLED: True
TEST:
  EVAL_PERIOD: 120000
DATASETS:
  TRAIN: ("lvis_v1_train_norare",)
SLEEP_TIME: 1000000