_BASE_: "base_r50_4x_clip.yaml"
MODEL:
  META_ARCHITECTURE: "CustomRCNN"
  MASK_ON: True
  ROI_BOX_HEAD:
    USE_ZEROSHOT_CLS: True
    ZEROSHOT_WEIGHT_DIM: 512
    ZEROSHOT_WEIGHT_PATH: 'checkpoints/mm_classifiers.pt'
    USE_BIAS: -2.0
  ROI_HEADS:
    NAME: MMDeticCascadeROIHeads
  WEIGHTS: "checkpoints/swin_base_patch4_window7_224_22k.pkl"
  BACKBONE:
    NAME: build_swintransformer_fpn_backbone
  SWIN:
    SIZE: B-22k
  FPN:
    IN_FEATURES: ["swin1", "swin2", "swin3"]
SOLVER:
  LR_SCHEDULER_NAME: "WarmupCosineLR"
  CHECKPOINT_PERIOD: 90000
  WARMUP_ITERS: 20000
  WARMUP_FACTOR: 0.0001
  USE_CUSTOM_SOLVER: True
  OPTIMIZER: "ADAMW"
  MAX_ITER: 180000
  IMS_PER_BATCH: 32
  BASE_LR: 0.0001
  CLIP_GRADIENTS:
    ENABLED: True
TEST:
  EVAL_PERIOD: 90000
INPUT:
  TRAIN_SIZE: 896
DATASETS:
  TRAIN: ("lvis_v1_train_norare",)
MAX_NUM_BOX:
  10
CLASSIFIER_NAME: "fusion"
SLEEP_TIME: 1000000