_BASE_: "base_r50_4x_clip.yaml"
MODEL:
  ROI_BOX_HEAD:
    USE_ZEROSHOT_CLS: True
    ZEROSHOT_WEIGHT_DIM: 768
    ZEROSHOT_WEIGHT_PATH: 'datasets/metadata/lvis_gpt3_text-davinci-002_features_author_vit-l-classname.npy'
    USE_BIAS: -2.0
SOLVER:
  LR_SCHEDULER_NAME: "WarmupCosineLR"
  CHECKPOINT_PERIOD: 180000
  WARMUP_ITERS: 36000
  WARMUP_FACTOR: 0.0001
  USE_CUSTOM_SOLVER: True
  OPTIMIZER: "ADAMW"
  STEPS: (120000,)
  MAX_ITER: 360000
  IMS_PER_BATCH: 16
  BASE_LR: 0.0002
  CLIP_GRADIENTS:
    ENABLED: True
TEST:
  EVAL_PERIOD: 180000
DATASETS:
  TRAIN: ("lvis_v1_train_norare",)
